from decimal import Decimal
from typing import Optional

from pydantic import BaseModel

from manta import MANTA_VERSION
from manta.messages import Status


class AckMessage(BaseModel):
    """
    Ack Message

    Order progress message.

    Published by the :term:`Payment Processor` on :ref:`acks/{session_id}`.

    Args:
        txid: progressive transaction ID generated by Merchant
        status: ack type
        url: url to be used for QR Code or NFC. Used in NEW
        amount: amount in crypto currency. Used in NEW
        transaction_hash: hash of transaction. After PENDING
        memo: extra text field
        version: Manta protocol version
    """

    txid: str
    status: Status
    url: Optional[str] = None
    amount: Optional[Decimal] = None
    transaction_hash: Optional[str] = None
    transaction_currency: Optional[str] = None
    memo: Optional[str] = None
    version: Optional[str] = MANTA_VERSION
